# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_url', models.URLField()),
                ('bootcamp_grad_hired', models.IntegerField()),
                ('contact', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
