# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp_recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='twitter_handle',
            field=models.CharField(default=datetime.datetime(2016, 3, 12, 22, 7, 35, 708874, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
